package org.basicdb;

import org.annotations.AutoGenerated;
import org.annotations.GreaterThan;
import org.annotations.NonNull;
import org.annotations.Unique;

public class IdHolder {
    @NonNull
    @GreaterThan(0)
    @Unique
    @AutoGenerated
    protected final Long id;

    public IdHolder(long id) {
        this.id = id;
    }
}
