package org.models;

import org.annotations.*;
import org.basicdb.SerializableComparator;

import java.io.Serializable;

public class Event implements Serializable, Comparable<Event> {
    @NonNull
    @GreaterThan(0)
    @Unique
    @AutoGenerated
    private Integer id;

    @NonNull
    @NonEmpty
    private String name;

    @NonNull
    @NonEmpty
    private String description;

    @NonNull
    private EventType eventType;


    @Override
    public int compareTo(Event o) {
        return SerializableComparator.instance.compare(this, o);
    }
}