package org.models;

import org.annotations.*;
import org.basicdb.IdHolder;
import org.basicdb.SerializableComparator;

import java.io.Serializable;
import java.util.Date;

public class Ticket extends IdHolder implements Serializable, Comparable<Ticket> {
    public Ticket(long id) {
        super(id);
    }

    @NonNull
    @NonEmpty
    public String name;

    @NonNull
    public Coordinates coordinates;

    @NonNull
    @AutoGenerated
    public Date creationDate;

    @GreaterThan(0)
    public long price;

    @NonNull
    @GreaterThan(0)
    @LowerThan(101)
    public Long discount;

    @NonNull
    public TicketType type;

    @NonNull
    public Event event;

    @Override
    public int compareTo(Ticket o) {
        return SerializableComparator.instance.compare(this, o);
    }
}