package org.models;

import org.annotations.*;
import org.basicdb.IdHolder;
import org.basicdb.SerializableComparator;

import java.io.Serializable;
import java.util.Date;

public class Ticket extends IdHolder implements Serializable, Comparable<Ticket> {
    public Ticket(long id) {
        super(id);
    }

    @NonNull
    @NonEmpty
    private String name;

    @NonNull
    private Coordinates coordinates;

    @NonNull
    @AutoGenerated
    private Date creationDate;

    @GreaterThan(0)
    private long price;

    @NonNull
    @GreaterThan(0)
    @LowerThan(101)
    private Long discount;

    @NonNull
    private TicketType type;

    @NonNull
    private Event event;

    @Override
    public int compareTo(Ticket o) {
        return SerializableComparator.instance.compare(this, o);
    }
}